### ISSUE TITLE
Use logo from R Ladies repository

### ISSUE THREAD

**Issue by mcanouil** [beatrizmilz/quarto-rladies-theme#2]
Maybe update the logo to use one from the official repository?

https://github.com/rladies/branding-materials

Maybe the following SVG?
https://github.com/rladies/branding-materials/blob/main/logo/R-LadiesGlobal_CMYK_offline_LogoWithText.svg

**Comment by beatrizmilz** [comment]
Hi! i figured it out what was going on! we dont need to use to logo from the official repo :D 
I documented better on how to use this on the readme file.
thank you!
