### ISSUE TITLE
Logo top right and bigger?

### ISSUE THREAD

**Issue by mcanouil** [beatrizmilz/quarto-rladies-theme#3]
I find the logo in the top right and slide number at the bottom right "better" so for my templates I switched them.
In case, it's a change you want to make: https://github.com/mcanouil/quarto-revealjs-coeos
Demo: https://m.canouil.fr/publishing-templates/quarto-coeos.html#/title-slide

**Comment by beatrizmilz** [comment]
Thanks!

I made that change and definetly looks better now!
