### ISSUE TITLE
inverse class for the quarto-rladies-theme

### ISSUE THREAD

**Issue by MMJansen** [beatrizmilz/quarto-rladies-theme#6]
Hi Beatriz, your quarto-rladies-theme extension is always the first thing I use when making an rladies pres. Today I added a `.inverse` class to the `scss`. Maybe you would like that as well to include in the `rladies.scss`? I added  
`.inverse {`
 `background-color: #562457 !important;`
  `$h1-color: white !important;`
 `$h2-color: white !important;`
  `$h3-color: white !important;`
`}`  
(Unfortunately I do not know yet how to do this officially as pull request :) , but it is just a few lines of code)

**Comment by beatrizmilz** [comment]
Thank you so much @MMJansen ! Let me know if now works in the way you expected :)
